# Generated by Django 3.1.3 on 2020-12-07 16:06

from django.db import migrations, models
import eshop_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0006_auto_20201207_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to=eshop_products.models.setGalleryFileName, verbose_name='تصویر'),
        ),
    ]
