# Generated by Django 3.1.3 on 2020-12-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitsetting',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='درباره ی ما'),
        ),
    ]
