# Generated by Django 3.1.3 on 2020-12-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0002_sitsetting_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SitSetting',
            new_name='SiteSetting',
        ),
    ]
