# Generated by Django 3.1.3 on 2020-12-05 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'دسنه بندی ها', 'verbose_name_plural': 'مدیریت دسته بندی ها'},
        ),
    ]
