# Generated by Django 3.1.3 on 2020-12-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0002_auto_20201208_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refID',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='کد پیگیری'),
        ),
    ]
